BEGIN;
DROP TABLE IF EXISTS agent_checkpoints;
DROP INDEX IF EXISTS agent_runs_run_key_uq;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS error_code;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS started_at;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS run_key;
ALTER TABLE agent_runs DROP COLUMN IF EXISTS project_id;
DROP INDEX IF EXISTS data_observations_project_idx;
ALTER TABLE data_observations DROP COLUMN IF EXISTS project_id;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS webhook_idempotency;
DROP TABLE IF EXISTS billing_customers;
DROP TABLE IF EXISTS project_members;
DROP INDEX IF EXISTS projects_org_idx;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DELETE FROM schema_migrations WHERE version='002_owned_platform_core';
COMMIT;
