import {NextRequest, NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {createHash} from 'node:crypto';
import {engineeringOrigin} from '@/lib/engineering-origin';
import {checkAndConsumeLlmRun, llmUsageMessage, type LlmUsagePlan} from '@/lib/llm-usage';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const ENGINE = engineeringOrigin();
const MODEL = process.env.OPENAI_MODEL || (process.env.OPENAI_API_BASE ? 'gpt-5.5' : 'gpt-5.6');
const BILLING_API = ENGINE;
const ALLOWED_OPERATIONS = new Set(['/v1/predict','/v1/simulate','/v1/calibrate','/v1/uncertainty','/v1/reverification','/v1/next-experiment','/v1/acceptance','/v1/agents/run','/v1/sim2real/run','/v1/sim2real/compare','/v1/final/risk','/v1/system-identification']);
const INTENT_SCHEMA = {type:'object',additionalProperties:false,properties:{operation:{type:'string',enum:Array.from(ALLOWED_OPERATIONS)},payload:{type:'object',additionalProperties:true},intent_summary:{type:'string'},entity:{type:['string','null']},resolved_dimensions_mm:{type:['object','null'],additionalProperties:false,properties:{width:{type:['number','null']},height:{type:['number','null']},depth:{type:['number','null']}},required:['width','height','depth']},evidence_sources:{type:'array',items:{type:'string'}},missing_information:{type:'array',items:{type:'string'}},confidence:{type:'number'}},required:['operation','payload','intent_summary','entity','resolved_dimensions_mm','evidence_sources','missing_information','confidence']} as const;
function sanitizePayload(value: unknown): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) return {}; const output: Record<string, unknown> = {}; for (const [key, raw] of Object.entries(value as Record<string, unknown>)) { if (key.length > 100) continue; if (typeof raw === 'string') output[key]=raw.slice(0,10000); else if (typeof raw==='number' && Number.isFinite(raw)) output[key]=raw; else if (typeof raw==='boolean'||raw===null) output[key]=raw; else if (Array.isArray(raw)) output[key]=raw.slice(0,100).map(v=>typeof v==='string'?v.slice(0,2000):v); else if (typeof raw==='object') output[key]=raw; } return output; }
function deterministicFallback(naturalLanguage: string, requestedOperation: string | undefined, suppliedPayload: Record<string, unknown>) { const operation = requestedOperation && ALLOWED_OPERATIONS.has(requestedOperation) ? requestedOperation : null; const text = naturalLanguage.toLowerCase(); const inferred = operation || (text.includes('simulate') ? '/v1/simulate' : text.includes('calibrat') ? '/v1/calibrate' : text.includes('uncertaint') ? '/v1/uncertainty' : text.includes('risk') ? '/v1/final/risk' : text.includes('accept') ? '/v1/acceptance' : text.includes('experiment') ? '/v1/next-experiment' : text.includes('reverif') ? '/v1/reverification' : text.includes('system ident') ? '/v1/system-identification' : text.includes('agent') ? '/v1/agents/run' : text.includes('sim2real') ? '/v1/sim2real/run' : text.includes('predict') ? '/v1/predict' : null); return {operation: inferred, payload: suppliedPayload, intent_summary: naturalLanguage.slice(0,500), entity:null, resolved_dimensions_mm:null, evidence_sources:[], missing_information: inferred ? [] : ['A specific engineering operation is needed because the AI reasoning service is unavailable.'], confidence: inferred ? 0.35 : 0.1}; }
async function resolveIntent(naturalLanguage:string, requestedOperation:string|undefined, suppliedPayload:Record<string,unknown>) { const apiKey=process.env.OPENAI_API_KEY || process.env.OPENROUTER_API_KEY || null; if (!apiKey) return {intent: deterministicFallback(naturalLanguage, requestedOperation, suppliedPayload), llm:{status:'unavailable',reason:'llm_not_configured'}}; const isOpenAI=Boolean(process.env.OPENAI_API_KEY); const base=isOpenAI ? (process.env.OPENAI_API_BASE||'https://api.openai.com/v1') : 'https://openrouter.ai/api/v1'; const url=isOpenAI ? `${base.replace(/\/$/,'')}/responses` : `${base}/chat/completions`; const instructions=`You are Fabrient's engineering intent layer. You provide semantic understanding only. Deterministic physics, geometry, rules and ML are authoritative. Never invent measurements. Preserve explicit numeric inputs. Choose only an allowed operation and return the supplied strict schema.`; const input=JSON.stringify({human_request:naturalLanguage.slice(0,12000),requested_operation:requestedOperation||null,supplied_payload:suppliedPayload,allowed_operations:Array.from(ALLOWED_OPERATIONS)}); try { const body:any=isOpenAI ? {model:MODEL,instructions,input,store:false,temperature:0,text:{format:{type:'json_schema',name:'fabrient_engineering_intent',strict:true,schema:INTENT_SCHEMA}}} : {model:process.env.OPENROUTER_MODEL||'openai/gpt-5.6',messages:[{role:'system',content:instructions},{role:'user',content:input}],temperature:0,response_format:{type:'json_object'}}; const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${apiKey}`},body:JSON.stringify(body),signal:AbortSignal.timeout(45000)}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(`LLM request failed (${response.status})`); const raw=isOpenAI ? (typeof data?.output_text==='string'?data.output_text:data?.output?.find((i:any)=>i?.type==='message')?.content?.find((c:any)=>c?.type==='output_text')?.text) : data?.choices?.[0]?.message?.content; if(!raw) throw new Error('LLM returned no intent'); const parsed=JSON.parse(raw); if(!ALLOWED_OPERATIONS.has(parsed.operation)) throw new Error('Unsupported operation'); parsed.payload=sanitizePayload(parsed.payload); for(const [k,v] of Object.entries(suppliedPayload)){if(typeof v==='number'&&Number.isFinite(v))parsed.payload[k]=v;} return {intent:parsed,llm:{status:'available',model:isOpenAI?MODEL:(process.env.OPENROUTER_MODEL||'openai/gpt-5.6')}}; } catch { return {intent:deterministicFallback(naturalLanguage,requestedOperation,suppliedPayload),llm:{status:'unavailable',reason:'llm_request_failed'}}; } }
async function runEngineering(operation:string,payload:Record<string,unknown>,requestId:string){const response=await fetch(`${ENGINE}${operation}`,{method:'POST',headers:{'content-type':'application/json','x-fabrient-request-id':requestId,'x-fabrient-orchestration':'llm+deterministic+ml'},body:JSON.stringify(payload),signal:AbortSignal.timeout(120000)});const body=await response.json().catch(()=>({}));return {ok:response.ok,status:response.status,body};}
async function getPlanAndUsageKey(){const token=(await cookies()).get('fabrient_session')?.value;if(!token)return null;try{const response=await fetch(`${BILLING_API}/billing/access`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:AbortSignal.timeout(5000)});if(!response.ok)return null;const body=await response.json().catch(()=>({}));const plan=body?.plan;return {key:createHash('sha256').update(token).digest('hex'),plan:(plan==='hobbyist'||plan==='startup'||plan==='enterprise'?plan:'free') as LlmUsagePlan};}catch{return null;}}
export async function POST(request:NextRequest){const requestId=request.headers.get('x-fabrient-request-id')||crypto.randomUUID();try{const access=await getPlanAndUsageKey();if(!access)return NextResponse.json({error:'Sign in before using the engineering copilot.'},{status:401});const body=await request.json();const naturalLanguage=typeof body?.naturalLanguage==='string'?body.naturalLanguage:'';const requestedOperation=typeof body?.operation==='string'?body.operation:undefined;const suppliedPayload=sanitizePayload(body?.payload);const execute=body?.execute!==false;if(!naturalLanguage&&!requestedOperation)return NextResponse.json({error:'Provide naturalLanguage or an operation.'},{status:400});if(requestedOperation&&!ALLOWED_OPERATIONS.has(requestedOperation))return NextResponse.json({error:'Unsupported engineering operation.'},{status:400});const usage=checkAndConsumeLlmRun(access.key,access.plan);if(!usage.allowed)return NextResponse.json({status:'usage_limited',error:usage.reason==='monthly_limit'?`You have used all ${usage.limit} free AI runs for this month.`:'You are using the copilot quickly. Please wait a few minutes and try again.',plan:access.plan,usage:{used:usage.used,limit:usage.limit,reset_at:new Date(usage.resetAt).toISOString()}},{status:429});const resolved=await resolveIntent(naturalLanguage||requestedOperation!,requestedOperation,suppliedPayload);const layers={llm:{model:resolved.llm.model||null,role:'semantic reasoning; advisory'},deterministic:{role:'authoritative physics/geometry/rules'},ml:{role:'calibration/system identification from real observations only'}};const intent=resolved.intent;if(!execute||intent.missing_information.length>0||!intent.operation)return NextResponse.json({status:intent.missing_information.length?'needs_input':'planned',request_id:requestId,intent,layers,usage:{used:usage.used,limit:usage.limit,message:llmUsageMessage(access.plan,usage.used,usage.limit)}});const result=await runEngineering(intent.operation,intent.payload,requestId);if(!result.ok)return NextResponse.json({status:'engineering_error',request_id:requestId,intent,layers,engineering:result.body,usage:{used:usage.used,limit:usage.limit,message:llmUsageMessage(access.plan,usage.used,usage.limit)}},{status:result.status});return NextResponse.json({status:'completed',request_id:requestId,intent,layers,engineering:result.body,usage:{used:usage.used,limit:usage.limit,message:llmUsageMessage(access.plan,usage.used,usage.limit)}});}catch(error:any){return NextResponse.json({status:'failed',request_id:requestId,error:error?.message||'Engineering orchestration failed'},{status:500});}}
