'use client';
import {useEffect,useState} from 'react';
type Provider={id:string;name:string;description:string;auth:string;endpoint:string;docs:string;configured?:boolean;kind?:string};type Tool={provider:string;name?:string;description?:string};type Connection={provider:string;connected:boolean;scopes:string[];expires_at:string|null};
export default function IntegrationsPage(){const[providers,setProviders]=useState<Provider[]>([]),[connections,setConnections]=useState<Connection[]>([]),[query,setQuery]=useState(''),[toolQuery,setToolQuery]=useState(''),[tools,setTools]=useState<Tool[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState<string|null>(null);
 async function load(q=''){try{const r=await fetch(`/integrations/search?query=${encodeURIComponent(q)}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Integration search failed');setProviders(data.results||[])}catch(e){setStatus(e instanceof Error?e.message:'Could not load integration catalog.')}}
 async function loadConnections(){try{const r=await fetch('/integrations/connections',{cache:'no-store'});if(r.ok){const data=await r.json();setConnections(data.connections||[])}}catch{}}
 useEffect(()=>{load();loadConnections();const p=new URLSearchParams(window.location.search);const connect=p.get('connect');const connected=p.get('connected');const oauthError=p.get('oauth_error');if(connected)setStatus(`${connected} connected.`);if(oauthError)setStatus(`Connection failed: ${oauthError}`);if(connect)connectProvider(connect)},[]);
 useEffect(()=>{const t=setTimeout(()=>load(query),180);return()=>clearTimeout(t)},[query]);
 useEffect(()=>{const t=setTimeout(async()=>{try{const r=await fetch(`/integrations/search-tools?query=${encodeURIComponent(toolQuery)}`);const data=await r.json();if(r.ok)setTools(data.tools||[])}catch{}},250);return()=>clearTimeout(t)},[toolQuery]);
 function isConnected(id:string){return connections.some(x=>x.provider===id&&x.connected)}
 async function connectProvider(provider:string){setBusy(provider);setStatus('Starting secure authorization…');try{const r=await fetch('/integrations/auth/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Unable to start connection');if(data.auth_url)window.location.assign(data.auth_url);else setStatus(`${provider}: no authorization is required.`)}catch(e){setStatus(e instanceof Error?e.message:'Connection failed');setBusy(null)}}
 async function disconnect(provider:string){setBusy(provider);try{const r=await fetch('/integrations/disconnect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider})});if(!r.ok)throw new Error('Disconnect failed');await loadConnections();setStatus(`${provider} disconnected.`)}catch(e){setStatus(e instanceof Error?e.message:'Disconnect failed')}finally{setBusy(null)}}
 return <main className="page-shell"><h1>Connect your tools</h1><p>Connect the tools Fabrient needs. One connection is shared by the web app and MCP, so you do not repeat setup.</p><section className="card"><h2>How connections work</h2><p>Choose Connect. Fabrient discovers the provider's supported OAuth flow, uses PKCE, and stores the resulting connection encrypted on the server. You never need to paste a client secret, API key, or MCP credential into Fabrient.</p></section><section className="card"><input aria-label="Search integrations" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search CAD, PLM, repositories, deployment…" /></section><section className="grid">{providers.map(p=>{const connected=isConnected(p.id);return <article className="card" key={p.id}><h2>{p.name}</h2><p>{p.description}</p><small>{p.kind?.replaceAll('_',' ')}</small><div style={{marginTop:12,display:'flex',gap:8}}><button disabled={busy===p.id||connected} onClick={()=>connectProvider(p.id)}>{busy===p.id?'Connecting…':connected?'Connected':'Connect'}</button>{connected&&<button disabled={busy===p.id} onClick={()=>disconnect(p.id)}>Disconnect</button>}</div></article>})}</section><section className="card"><h2>Use connected tools</h2><p>Search the live tools exposed by your connected official MCP providers. The agent chooses the underlying tool; you describe the outcome you want.</p><input aria-label="Search connected tools" value={toolQuery} onChange={e=>setToolQuery(e.target.value)} placeholder="e.g. import repository files" />{tools.length>0&&<ul>{tools.map((t,i)=><li key={`${t.provider}-${t.name}-${i}`}><strong>{t.name}</strong> — {t.description} <small>({t.provider})</small></li>)}</ul>}</section>{connections.length>0&&<section className="card"><h2>Your connections</h2>{connections.map(c=><p key={c.provider}><strong>{c.provider}</strong> — connected{c.scopes.length?` · ${c.scopes.join(', ')}`:''}</p>)}</section>}{status&&<p role="status">{status}</p>}</main>}
