'use client';
import {useEffect,useState} from 'react';
type Provider={id:string;name:string;description:string;auth:string;endpoint:string;docs:string;configured?:boolean;kind?:string};type Tool={provider:string;name?:string;description?:string};
const MCP_URL='https://fabrient-mcp.onrender.com/mcp';
const clients=[
  ['ChatGPT','Add a remote MCP server in the client connector/developer settings, paste the URL, authenticate, then verify that Fabrient tools are listed.'],
  ['Claude','Add a remote MCP server in Claude MCP settings, paste the URL, authenticate, then restart/reload the client if the tool list does not appear.'],
  ['Codex','Add a remote HTTP/Streamable HTTP MCP server with this URL in Codex MCP configuration. Keep secrets in the client environment, never in source.'],
  ['Cursor','Open Cursor Settings → MCP, add a remote HTTP server, paste the URL, save, and confirm Fabrient appears in the connected-server list.'],
  ['VS Code','Add Fabrient as a remote MCP server in the MCP configuration used by your VS Code build, then verify the server initializes successfully.'],
  ['Other MCP clients','Choose Streamable HTTP/remote MCP, paste the URL, complete authentication, and confirm the server initializes and exposes the expected tools.'],
] as const;
export default function IntegrationsPage(){const[providers,setProviders]=useState<Provider[]>([]),[query,setQuery]=useState(''),[toolQuery,setToolQuery]=useState(''),[tools,setTools]=useState<Tool[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState<string|null>(null),[copied,setCopied]=useState(false);
 async function load(q=''){try{const r=await fetch(`/integrations/search?query=${encodeURIComponent(q)}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Integration search failed');setProviders(data.results||[])}catch(e){setStatus(e instanceof Error?e.message:'Could not load integration catalog.')}} useEffect(()=>{load()},[]);useEffect(()=>{const t=setTimeout(()=>load(query),180);return()=>clearTimeout(t)},[query]);useEffect(()=>{const t=setTimeout(async()=>{try{const r=await fetch(`/integrations/search-tools?query=${encodeURIComponent(toolQuery)}`);const data=await r.json();if(r.ok)setTools(data.tools||[])}catch{}},250);return()=>clearTimeout(t)},[toolQuery]);
 async function connect(p:Provider){setBusy(p.id);setStatus('');try{const r=await fetch('/integrations/auth/start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:p.id})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Unable to start connection');if(data.auth_url)window.open(data.auth_url,'_blank','noopener,noreferrer');else if(data.docs)window.open(data.docs,'_blank','noopener,noreferrer');setStatus(`${p.name}: authorization flow opened.`)}catch(e){setStatus(e instanceof Error?e.message:'Connection failed')}finally{setBusy(null)}}
 async function copyMcp(){try{await navigator.clipboard.writeText(MCP_URL);setCopied(true);setStatus('MCP URL copied.');setTimeout(()=>setCopied(false),1800)}catch{setStatus('Copy failed; select the URL manually.')}}
 return <main className="page-shell"><h1>Connect your tools</h1><p>Connect Fabrient to MCP-compatible clients while keeping the engineering evidence boundary intact.</p>
 <section className="card"><h2>Fabrient MCP server</h2><p>One remote endpoint for the authenticated engineering tool surface.</p><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><code aria-label="Fabrient MCP URL" style={{padding:'12px',border:'1px solid currentColor',borderRadius:8,overflowWrap:'anywhere'}}>{MCP_URL}</code><button onClick={copyMcp}>{copied?'Copied ✓':'Copy MCP URL'}</button></div><div style={{display:'grid',gap:12,marginTop:16}}>{clients.map(([name,instructions])=><details key={name}><summary><strong>{name}</strong></summary><p>{instructions}</p><code style={{display:'block',whiteSpace:'pre-wrap',padding:10}}>{MCP_URL}</code></details>)}</div><p className="muted" style={{marginTop:12}}>MCP supports Streamable HTTP for remote servers; clients can expose tools, resources and prompts through the same protocol surface. Use the client's current MCP settings rather than copying credentials into the app.</p></section>
 <section className="card"><input aria-label="Search integrations" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search CAD, PLM, documentation, repositories…" /></section><section className="grid">{providers.map(p=><article className="card" key={p.id}><h2>{p.name}</h2><p>{p.description}</p><small>{p.kind?.replaceAll('_',' ')}</small><div><button disabled={busy===p.id} onClick={()=>connect(p)}>{busy===p.id?'Opening…':p.configured?'Connected':'Connect'}</button></div></article>)}</section>
 <section className="card"><h2>Find a tool for the job</h2><p>Search live tool names and descriptions from connected official MCP servers.</p><input aria-label="Search connected tools" value={toolQuery} onChange={e=>setToolQuery(e.target.value)} placeholder="e.g. inspect repository" />{tools.length>0&&<ul>{tools.map((t,i)=><li key={`${t.provider}-${t.name}-${i}`}><strong>{t.name}</strong> — {t.description} <small>({t.provider})</small></li>)}</ul>}</section>{status&&<p role="status">{status}</p>}</main>}
