import {createBrowserSupabase} from '@/lib/supabase-browser';

export type LoopState={stage:'analyze'|'review'|'build'|'inspect'|'reverify'|'released';next_action:string;status:'active'|'blocked'|'ready'|'released';unresolved_issues:any[];evidence_summary:Record<string,any>;last_action:string};
const KEY='fabrient:engineering-loop:v1';
const fallback:LoopState={stage:'analyze',next_action:'Run your first deterministic check.',status:'active',unresolved_issues:[],evidence_summary:{},last_action:'Opened workspace'};
export function loadLocalLoop():LoopState{try{return {...fallback,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return fallback}}
export function saveLocalLoop(state:LoopState){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
export async function loadLoop():Promise<LoopState>{const local=loadLocalLoop();try{const supabase=createBrowserSupabase();if(!supabase)return local;const{data:{user}}=await supabase.auth.getUser();if(!user)return local;const{data,error}=await supabase.from('engineering_loop_state').select('*').eq('user_id',user.id).maybeSingle();if(error||!data)return local;const state:{stage:LoopState['stage'];next_action:string;status:LoopState['status'];unresolved_issues:any[];evidence_summary:Record<string,any>;last_action:string}={stage:data.stage,next_action:data.next_action,status:data.status,unresolved_issues:data.unresolved_issues||[],evidence_summary:data.evidence_summary||{},last_action:data.last_action||''};saveLocalLoop(state);return state}catch{return local}}
export async function saveLoop(state:LoopState){saveLocalLoop(state);try{const supabase=createBrowserSupabase();if(!supabase)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;await supabase.from('engineering_loop_state').upsert({user_id:user.id,stage:state.stage,next_action:state.next_action,status:state.status,unresolved_issues:state.unresolved_issues,evidence_summary:state.evidence_summary,last_action:state.last_action},{onConflict:'user_id'});}catch{/* local state remains a safe offline fallback */}}
