'use client';
import {useState} from 'react';
const ENGINE='/api/engineering';
type Obs={predicted_mm:number;measured_mm:number;layer_height_mm?:number;print_speed_mm_s?:number;nozzle_temp_c?:number;ambient_temp_c?:number;humidity_pct?:number;axis?:number;machine_id?:string;feature_id?:string;experiment_id?:string};
function parseRows(text:string):Obs[]{
  const value=JSON.parse(text);
  const rows=Array.isArray(value)?value:(Array.isArray(value.observations)?value.observations:[]);
  return rows.map((r:any)=>({predicted_mm:Number(r.predicted_mm??r.predicted),measured_mm:Number(r.measured_mm??r.measured),layer_height_mm:Number(r.layer_height_mm??.2),print_speed_mm_s:Number(r.print_speed_mm_s??50),nozzle_temp_c:Number(r.nozzle_temp_c??200),ambient_temp_c:Number(r.ambient_temp_c??23),humidity_pct:Number(r.humidity_pct??50),axis:Number(r.axis??0),machine_id:r.machine_id,feature_id:r.feature_id,experiment_id:r.experiment_id})).filter((r:Obs)=>Number.isFinite(r.predicted_mm)&&Number.isFinite(r.measured_mm));
}
export default function Sim2Real(){
 const [observations,setObservations]=useState<Obs[]>([]); const [result,setResult]=useState<any>(); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [nominal,setNominal]=useState(10);
 async function load(file:File){try{setError('');setObservations(parseRows(await file.text()))}catch(e:any){setError(e?.message||'Could not read experiment data. Use JSON with an observations array.')}}
 async function run(){setBusy(true);setError('');try{const r=await fetch(`${ENGINE}/v1/sim2real/calibrate-and-run`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({nominal_mm:nominal,observations})});const j=await r.json();if(!r.ok)throw Error(j.detail||`Engineering service failed (${r.status})`);setResult(j)}catch(e:any){setError(e?.message||'Reality loop failed')}finally{setBusy(false)}}
 const c=result?.comparison||result?.prediction_vs_reality; const cal=result?.calibration||{}; const trust=result?.trust_envelope; const next=result?.next_action||result?.next_experiment;
 return <main className="page wide"><div className="eyebrow">FABRIENT / REALITY LOOP</div><h1 className="title">Make simulation agree with reality.</h1><p className="muted" style={{maxWidth:900}}>Fabrient compares simulation predictions with real experiments, calibrates a physics baseline, learns residual error with ML, validates on held-out data, and chooses the next information-gaining experiment. No synthetic measurements are accepted.</p>
 <section className="panel" style={{marginTop:24}}><div className="workspace-grid"><div><h2>ONE INPUT</h2><label>Baseline nominal value<input type="number" value={nominal} onChange={e=>setNominal(Number(e.target.value))}/></label><label>Experiment data (.json)<input type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];if(f)load(f)}}/></label><p className="muted">Drop one exported experiment dataset. Fabrient derives the repeated model inputs from the data instead of asking you to re-enter every run.</p><button className="button primary" disabled={busy||!observations.length} onClick={run}>{busy?'Running autonomous calibration…':'Run reality loop'}</button>{error&&<p className="error" role="alert">{error}</p>}</div><div><h2>LOOP STATUS</h2><p><strong>{observations.length}</strong> real observations loaded</p><p className="muted">{observations.length<8?'Calibration waits for enough real evidence.':observations.length<10?'Calibration can run, but held-out validation is not yet strong enough for a validated claim.':'Independent validation can be evaluated.'}</p></div></div></section>
 {result&&<><section className="grid grid3" style={{marginTop:24}}><article className="panel"><div className="eyebrow">REALITY GAP</div><h2>{c?.mae!=null?`${Number(c.mae).toFixed(4)} mm`:'—'}</h2><p className="muted">MAE · RMSE {c?.rmse!=null?Number(c.rmse).toFixed(4):'—'} mm</p></article><article className="panel"><div className="eyebrow">ML MODEL</div><h2>{cal.status||'not ready'}</h2><p className="muted">Held-out MAE {cal.held_out_mae!=null?Number(cal.held_out_mae).toFixed(4):'—'} mm</p></article><article className="panel"><div className="eyebrow">TRUST ENVELOPE</div><h2>{trust?.confidence!=null?`${Math.round(Number(trust.confidence)*100)}%`:'—'}</h2><p className="muted">Observed validation conditions only.</p></article></section>
 <section className="workspace-grid" style={{marginTop:24}}><div className="panel"><h2>WHAT DIVERGED</h2><pre className="provenance">{JSON.stringify(c?.worst||c?.divergence,null,2)}</pre></div><div className="panel"><h2>WHAT NEXT</h2><pre className="provenance">{JSON.stringify(next,null,2)}</pre></div></section>
 <section className="panel" style={{marginTop:24}}><h2>PROVENANCE</h2><p className="muted">{result.evidence_policy||'Real observations only.'}</p><p className="muted">Input fingerprint: {result.input_fingerprint||result.provenance?.input_fingerprint||'—'}</p><p className="muted">Status: <strong>{result.status}</strong></p></section></>}
 </main>
}
