'use client';
import {useState} from 'react';
const ENGINE='/api/engineering';
type Result=any; type ZipFile={name:string;data:Uint8Array};
function crc32(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0} function u16(n:number){return new Uint8Array([n&255,(n>>>8)&255])} function u32(n:number){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])} function concat(parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out} function makeZip(files:ZipFile[]){const enc=new TextEncoder(),chunks:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;for(const file of files){const name=enc.encode(file.name),crc=crc32(file.data),local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(file.data.length),u32(file.data.length),u16(name.length),u16(0),name,file.data]);chunks.push(local);central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(file.data.length),u32(file.data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const cd=concat(central),body=concat(chunks);return concat([body,cd,concat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(body.length),u16(0)])])} function downloadBytes(name:string,data:Uint8Array,type='application/octet-stream'){const blob=new Blob([data as unknown as BlobPart],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export default function Manufacturing(){
 const [part,setPart]=useState('Electronics enclosure'),[revision,setRevision]=useState('A'),[material,setMaterial]=useState('PETG'),[machine,setMachine]=useState('FDM printer');
 const [dims,setDims]=useState({width_mm:40,depth_mm:20,height_mm:10,wall_mm:1.2,clearance_mm:.25,mounting_hole_diameter_mm:2.4,mounting_hole_inset_mm:5});
 const [measurements,setMeasurements]=useState({wall_thickness_mm:1.0,clearance_mm:.15,hole_diameter_mm:2.4,overhang_deg:55,bridge_mm:8,tolerance_mm:.2});
 const [cadFile,setCadFile]=useState<File|null>(null),[generatedStep,setGeneratedStep]=useState<{name:string,data:Uint8Array,validation:any}|null>(null),[result,setResult]=useState<Result>(),[guide,setGuide]=useState<Result>(),[pkg,setPkg]=useState<Result>();const[busy,setBusy]=useState(false),[error,setError]=useState(''),[advanced,setAdvanced]=useState(false),[cadStatus,setCadStatus]=useState('STEP required before engineering release.');
 const update=(k:string,v:string)=>setMeasurements(x=>({...x,[k]:Number(v)})); const updateDim=(k:string,v:string)=>setDims(x=>({...x,[k]:Number(v)}));
 async function post(path:string,body:any){const r=await fetch(`${ENGINE}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const text=await r.text();let j:any;try{j=JSON.parse(text)}catch{j={detail:`Engineering service returned a non-JSON response (${r.status}).`}}if(!r.ok)throw new Error(j.detail||j.message||j.error||`Engineering request failed (${r.status})`);return j}
 async function validateFile(file:File){const fd=new FormData();fd.append('file',file);const r=await fetch(`${ENGINE}/v1/geometry/step`,{method:'POST',body:fd,cache:'no-store'});const text=await r.text();let j:any;try{j=JSON.parse(text)}catch{j={detail:text}}if(!r.ok)throw new Error(j.detail||j.reason||'STEP validation failed');if(j.status!=='validated')throw new Error('STEP did not pass full OCCT topology validation');return j}
 async function generateCad(){setBusy(true);setError('');try{const g=await post('/v1/geometry/generate',{...dims,revision,material});const bytes=Uint8Array.from(atob(g.step_base64),c=>c.charCodeAt(0));setGeneratedStep({name:g.filename,data:bytes,validation:g.validation});setCadFile(null);setCadStatus(`Generated and round-trip validated: ${g.filename}`);downloadBytes(g.filename,bytes,'application/step')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function ensureCad(){if(generatedStep)return generatedStep.validation;if(!cadFile)throw new Error('A validated STEP file is required. Generate CAD or attach a .step/.stp file.');const v=await validateFile(cadFile);setCadStatus(`Validated STEP: ${cadFile.name}`);return v}
 async function analyze(){setBusy(true);setError('');try{await ensureCad();setResult(await post('/v1/dfm/analyze',{part_name:part,revision,material,machine,measurements,cad_required:true,cad_filename:generatedStep?.name||cadFile?.name}));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function selfFix(){setBusy(true);setError('');try{await ensureCad();setResult(await post('/v1/dfm/self-fix',{part_name:part,revision,material,machine,measurements,cad_required:true,cad_filename:generatedStep?.name||cadFile?.name}));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function generateGuide(){setBusy(true);setError('');try{await ensureCad();setGuide(await post('/v1/manufacturing/build-guide',{project_name:part,revision,material,machine,dfm_result:result?.after||result}));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function packageIt(){setBusy(true);setError('');try{await ensureCad();const dfm=result?.after||result,p=await post('/v1/manufacturing/package',{project_name:part,revision,material,machine,dfm_result:dfm,source_files:[generatedStep?.name||cadFile?.name||'']});setPkg(p);const g=guide||await post('/v1/manufacturing/build-guide',{project_name:part,revision,material,machine,dfm_result:dfm});if(!guide)setGuide(g);const enc=new TextEncoder(),cadData=generatedStep?.data||new Uint8Array(await cadFile!.arrayBuffer());const files:ZipFile[]=[{name:'release_manifest.json',data:enc.encode(JSON.stringify({...p,step_required:true,validated_step:generatedStep?.name||cadFile?.name,step_round_trip_validated:true},null,2))},{name:'dfm_report.json',data:enc.encode(JSON.stringify(dfm,null,2))},{name:'physical_build_guide.md',data:enc.encode(g.guide_markdown||'')},{name:'manufacturing_notes.md',data:enc.encode(`# ${part} — Manufacturing notes\n\n- Revision: ${revision}\n- Material: ${material}\n- Machine: ${machine}\n- STEP: validated\n- Release status: ${p.release_status}\n`)},{name:'inspection_plan.csv',data:enc.encode('feature,nominal_mm,measured_mm,result\n')},{name:`cad/${generatedStep?.name||cadFile?.name}`,data:cadData}];downloadBytes(`${part.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}-manufacturing-package-r${revision}.zip`,makeZip(files),'application/zip')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const hasCad=Boolean(generatedStep||cadFile); return <main className="page wide"><div className="eyebrow">MANUFACTURING / RELEASE</div><h1 className="title">Fix it. Verify it. Build it.</h1><p className="muted" style={{maxWidth:860}}>A manufacturing release is impossible without a real, kernel-validated STEP file. Generate one here or attach an existing STEP.</p>
 <div className="workspace-grid" style={{marginTop:28}}><section className="panel"><h2>1 / PART INPUT</h2><label>Part name<input value={part} onChange={e=>setPart(e.target.value)}/></label><label>Revision<input value={revision} onChange={e=>setRevision(e.target.value)}/></label><label>Material<input value={material} onChange={e=>setMaterial(e.target.value)}/></label><label>Machine<input value={machine} onChange={e=>setMachine(e.target.value)}/></label><label>Validated CAD — REQUIRED<input type="file" accept=".step,.stp" onChange={e=>{setCadFile(e.target.files?.[0]||null);setGeneratedStep(null);setCadStatus('STEP selected; validation will run before any engineering action.')}}/></label><div className="panel" style={{marginTop:12}}><strong>CAD generation</strong><p className="muted">Generate a deterministic parametric enclosure and require an OCCT STEP round trip before it can be used.</p><div className="formgrid">{Object.entries(dims).map(([k,v])=><label key={k}>{k}<input type="number" step="0.01" value={v} onChange={e=>updateDim(k,e.target.value)}/></label>)}</div><button className="button" disabled={busy} onClick={generateCad}>Generate + validate STEP</button></div><p className="muted" role="status">{cadStatus}</p><details open={advanced} onToggle={e=>setAdvanced((e.currentTarget as HTMLDetailsElement).open)} style={{marginTop:20}}><summary style={{cursor:'pointer',fontWeight:700}}>Advanced manufacturing limits</summary><p className="muted">Only change these when you have measured or process-specific values.</p>{Object.entries(measurements).map(([k,v])=><label key={k}>{k}<input type="number" step="0.01" value={v} onChange={e=>update(k,e.target.value)}/></label>)}</details><div className="row" style={{marginTop:16}}><button className="button" disabled={busy||!hasCad} onClick={analyze}>Analyze</button><button className="button primary" disabled={busy||!hasCad} onClick={selfFix}>Self-fix + verify</button></div>{error&&<p className="error" role="alert">{error}</p>}</section>
 <section className="panel"><h2>2 / WHAT FABRIENT FIXED</h2>{!result&&<p className="muted">No engineering result is accepted until STEP validation succeeds.</p>}{result?.changes?.length>0&&result.changes.map((c:any,i:number)=><div className="panel" key={i}><strong>{c.issue}</strong><p className="muted">{c.field}: {c.before} → {c.after}</p><p>{c.reason}</p></div>)}{result?.refused?.length>0&&<><h3>Human/CAD fixes required</h3>{result.refused.map((x:any,i:number)=><p className="muted" key={i}>• {x.finding?.code}: {x.reason}</p>)}</>}{result?.after&&<div className="panel"><strong>Verification: {result.after.status}</strong><p>{result.after.blocker_count} blocker(s) remain.</p></div>}</section></div>
 <section className="panel" style={{marginTop:24}}><h2>3 / PHYSICAL BUILD GUIDE</h2><p className="muted">One simple sequence for the person who will actually build the validated part.</p><button className="button" disabled={!result||busy||!hasCad} onClick={generateGuide}>Generate build guide</button>{guide?.steps?.map((s:any)=><div className="panel" key={s.step}><strong>Step {s.step}: {s.title}</strong><p>{s.action}</p>{s.check&&<p className="muted">Check: {s.check}</p>}</div>)}{guide?.guide_markdown&&<button className="button" onClick={()=>downloadBytes(`${part.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}-physical-build-guide.md`,new TextEncoder().encode(guide.guide_markdown),'text/markdown')}>Download guide</button>}</section>
 <section className="panel" style={{marginTop:24}}><div className="row" style={{justifyContent:'space-between'}}><div><h2>4 / FINAL MANUFACTURING PACKAGE</h2><p className="muted">Release is gated on a validated STEP and completed DFM workflow.</p></div><button className="button primary" disabled={!result||busy||!hasCad} onClick={packageIt}>Generate final package</button></div>{pkg&&<div style={{marginTop:18}}><div className="grid grid3">{pkg.contents?.map((x:any)=><div className="panel" key={x.name}><strong>{x.name}</strong><p className="muted">{x.type}</p></div>)}</div><pre className="provenance">{JSON.stringify(pkg.gates,null,2)}</pre><p className="muted">Manifest SHA-256: {pkg.manifest_sha256}</p></div>}</section></main>
}
