'use client';
import Link from 'next/link';import {useState} from 'react';

const ENGINE='/api/engineering';
type Result=any;
type ZipFile={name:string;data:Uint8Array};
function crc32(bytes:Uint8Array){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function u16(n:number){return new Uint8Array([n&255,(n>>>8)&255])}
function u32(n:number){return new Uint8Array([n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255])}
function concat(parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((n,p)=>n+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function makeZip(files:ZipFile[]){const enc=new TextEncoder();const chunks:Uint8Array[]=[];const central:Uint8Array[]=[];let offset=0;for(const file of files){const name=enc.encode(file.name);const crc=crc32(file.data);const local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(file.data.length),u32(file.data.length),u16(name.length),u16(0),name,file.data]);chunks.push(local);central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(file.data.length),u32(file.data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const cd=concat(central);const body=concat(chunks);const end=concat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(body.length),u16(0)]);return concat([body,cd,end])}
function downloadBytes(name:string,data:Uint8Array,type='application/octet-stream'){const blob=new Blob([data as unknown as BlobPart],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
export default function Manufacturing(){
  const [part,setPart]=useState('Electronics enclosure');const [revision,setRevision]=useState('A');const [material,setMaterial]=useState('PETG');const [machine,setMachine]=useState('FDM printer');
  const [measurements,setMeasurements]=useState({wall_thickness_mm:1.0,clearance_mm:0.15,hole_diameter_mm:2.4,overhang_deg:55,bridge_mm:8,tolerance_mm:0.2});const [cadFile,setCadFile]=useState<File|null>(null);const [result,setResult]=useState<Result>();const [guide,setGuide]=useState<Result>();const [pkg,setPkg]=useState<Result>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [advanced,setAdvanced]=useState(false);
  const update=(k:string,v:string)=>setMeasurements(x=>({...x,[k]:Number(v)}));
  async function post(path:string,body:any){const r=await fetch(`${ENGINE}${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const text=await r.text();let j:any;try{j=JSON.parse(text)}catch{j={detail:`Engineering service returned a non-JSON response (${r.status}).`}}if(!r.ok)throw new Error(j.detail||j.message||`Engineering request failed (${r.status})`);return j;}
  async function analyze(){setBusy(true);setError('');try{setResult(await post('/v1/dfm/analyze',{part_name:part,revision,material,machine,measurements}));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function selfFix(){setBusy(true);setError('');try{setResult(await post('/v1/dfm/self-fix',{part_name:part,revision,material,machine,measurements}));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function generateGuide(){setBusy(true);setError('');try{setGuide(await post('/v1/manufacturing/build-guide',{project_name:part,revision,material,machine,dfm_result:result?.after||result}));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function packageIt(){setBusy(true);setError('');try{const dfm=result?.after||result;const p=await post('/v1/manufacturing/package',{project_name:part,revision,material,machine,dfm_result:dfm,source_files:cadFile?[cadFile.name]:[]});setPkg(p);const g=guide||await post('/v1/manufacturing/build-guide',{project_name:part,revision,material,machine,dfm_result:dfm});if(!guide)setGuide(g);const enc=new TextEncoder();const files:ZipFile[]=[{name:'release_manifest.json',data:enc.encode(JSON.stringify({...p,source_cad_attached:Boolean(cadFile),source_cad_filename:cadFile?.name||null},null,2))},{name:'dfm_report.json',data:enc.encode(JSON.stringify(dfm,null,2))},{name:'physical_build_guide.md',data:enc.encode(g.guide_markdown||'')},{name:'manufacturing_notes.md',data:enc.encode(`# ${part} — Manufacturing notes\n\n- Revision: ${revision}\n- Material: ${material}\n- Machine: ${machine}\n- Release status: ${p.release_status}\n\nReview the DFM gates and the physical build guide before production. Fabrient does not silently authorize physical production.\n`)},{name:'inspection_plan.csv',data:enc.encode('feature,nominal_mm,measured_mm,result\n')},{name:'source_cad.README.txt',data:enc.encode(cadFile?'The supplied CAD file is included under source_cad/.':'No CAD file was attached. Attach the validated source CAD before manufacturing release.')}];if(cadFile)files.push({name:`source_cad/${cadFile.name}`,data:new Uint8Array(await cadFile.arrayBuffer())});downloadBytes(`${part.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}-manufacturing-package-r${revision}.zip`,makeZip(files),'application/zip');}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <main className="page wide"><div className="eyebrow">MANUFACTURING / RELEASE</div><h1 className="title">Fix it. Verify it. Build it.</h1><p className="muted" style={{maxWidth:860}}>Start with the few things Fabrient actually needs. Advanced manufacturing limits stay optional and hidden until you need them.</p>
    <div className="workspace-grid" style={{marginTop:28}}><section className="panel"><h2>1 / PART INPUT</h2><label>Part name<input value={part} onChange={e=>setPart(e.target.value)}/></label><label>Revision<input value={revision} onChange={e=>setRevision(e.target.value)}/></label><label>Material<input value={material} onChange={e=>setMaterial(e.target.value)}/></label><label>Machine<input value={machine} onChange={e=>setMachine(e.target.value)}/></label><label>Validated CAD (optional)<input type="file" accept=".step,.stp,.stl,.3mf" onChange={e=>setCadFile(e.target.files?.[0]||null)}/></label><details open={advanced} onToggle={e=>setAdvanced((e.currentTarget as HTMLDetailsElement).open)} style={{marginTop:20}}><summary style={{cursor:'pointer',fontWeight:700}}>Advanced manufacturing limits</summary><p className="muted">Only change these when you have measured or process-specific values. Defaults are deliberately conservative.</p>{Object.entries(measurements).map(([k,v])=><label key={k}>{k}<input type="number" step="0.01" value={v} onChange={e=>update(k,e.target.value)}/></label>)}</details><div className="row" style={{marginTop:16}}><button className="button" disabled={busy} onClick={analyze}>Analyze</button><button className="button primary" disabled={busy} onClick={selfFix}>Self-fix + verify</button></div>{error&&<p className="error" role="alert">{error}</p>}</section>
      <section className="panel"><h2>2 / WHAT FABRIENT FIXED</h2>{!result&&<p className="muted">Run the self-fix pass to see before → after changes and remaining blockers.</p>}{result?.changes?.length>0&&<div>{result.changes.map((c:any,i:number)=><div className="panel" key={i}><strong>{c.issue}</strong><p className="muted">{c.field}: {c.before} → {c.after}</p><p>{c.reason}</p></div>)}</div>}{result?.changes?.length===0&&result&&<p>No deterministic scalar changes were necessary.</p>}{result?.refused?.length>0&&<><h3>Human/CAD fixes required</h3>{result.refused.map((x:any,i:number)=><p className="muted" key={i}>• {x.finding?.code}: {x.reason}</p>)}</>}{result?.after&&<div className="panel"><strong>Verification: {result.after.status}</strong><p>{result.after.blocker_count} blocker(s) remain.</p></div>}{error.includes('(401)')&&<div className="panel"><strong>Sign in to run engineering actions.</strong><p className="muted">Your inputs are preserved on this page. Authentication is required before the backend can analyze or change engineering state.</p><Link className="button primary" href="/login?redirect=/manufacturing">Sign in to continue</Link></div>}</section></div>
    <section className="panel" style={{marginTop:24}}><h2>3 / PHYSICAL BUILD GUIDE</h2><p className="muted">One simple sequence for the person who will actually build the part.</p><button className="button" disabled={!result||busy} onClick={generateGuide}>Generate build guide</button>{guide?.steps?.map((s:any)=><div className="panel" key={s.step}><strong>Step {s.step}: {s.title}</strong><p>{s.action}</p>{s.check&&<p className="muted">Check: {s.check}</p>}</div>)}{guide?.guide_markdown&&<button className="button" onClick={()=>downloadBytes(`${part.replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()}-physical-build-guide.md`,new TextEncoder().encode(guide.guide_markdown),'text/markdown')}>Download guide</button>}</section>
    <section className="panel" style={{marginTop:24}}><div className="row" style={{justifyContent:'space-between'}}><div><h2>4 / FINAL MANUFACTURING PACKAGE</h2><p className="muted">Generate this only after the DFM result exists. Attach validated CAD if it belongs in the release package.</p></div><button className="button primary" disabled={!result||busy} onClick={packageIt}>Generate final package</button></div>{pkg&&<div style={{marginTop:18}}><div className="grid grid3">{pkg.contents?.map((x:any)=><div className="panel" key={x.name}><strong>{x.name}</strong><p className="muted">{x.type}</p></div>)}</div><pre className="provenance">{JSON.stringify(pkg.gates,null,2)}</pre><p className="muted">Manifest SHA-256: {pkg.manifest_sha256}</p><p className="muted">The ZIP was downloaded when generation completed.</p></div>}</section>
  </main>
}
