'use client'

import dynamic from 'next/dynamic'
import Link from 'next/link'
import {useEffect, useMemo, useState} from 'react'

const View3D = dynamic(() => import('@/components/geometry-viewer'), {ssr: false, loading: () => <div className="viewer"><div className="viewer-label">Loading verified 3D view…</div></div>})
const ENGINE = '/api/engineering'
const REQUEST_TIMEOUT_MS = 120_000

type Prediction = {prediction_mm:number; interval_95_mm:number[]; physics_uncertainty_mm:number; status:string; provenance:unknown}

async function request(path:string, init:RequestInit={}) {
  const controller = new AbortController(); const timer = window.setTimeout(()=>controller.abort(), REQUEST_TIMEOUT_MS)
  try {
    const response = await fetch(`${ENGINE}${path}`, {...init, signal:controller.signal, headers:{'content-type':'application/json', ...(init.headers||{})}, cache:'no-store'})
    const text = await response.text(); let body:any={}; try {body=text?JSON.parse(text):{}} catch {body={detail:text}}
    if (!response.ok) throw new Error(body.detail||body.reason||body.error||`Engineering service returned ${response.status}`)
    return body
  } catch (error:any) { if(error?.name==='AbortError') throw new Error('The engineering service timed out. No result was accepted.'); throw error }
  finally {window.clearTimeout(timer)}
}

export default function Workspace(){
  const [nominal,setNominal]=useState(40),[shrink,setShrink]=useState(.5),[sigma,setSigma]=useState(.15),[material,setMaterial]=useState('PETG'),[machine,setMachine]=useState('Machine 01'),[temp,setTemp]=useState(245),[tolerance,setTolerance]=useState(.4)
  const [prediction,setPrediction]=useState<Prediction|null>(null),[service,setService]=useState<'checking'|'ready'|'blocked'>('checking'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[lastAction,setLastAction]=useState('Start with the deterministic check below.')
  useEffect(()=>{let cancelled=false;request('/health',{method:'GET'}).then(()=>!cancelled&&setService('ready')).catch(()=>!cancelled&&setService('blocked'));return()=>{cancelled=true}},[])
  async function predict(){setBusy(true);setError('');setLastAction('Running deterministic engineering check…');try{const result=await request('/v1/predict',{method:'POST',body:JSON.stringify({nominal_mm:nominal,material,machine,process_temperature_c:temp,nominal_shrinkage_pct:shrink,shrinkage_uncertainty_pct:sigma,tolerance_lower_mm:-tolerance/2,tolerance_upper_mm:tolerance/2})});if(!Number.isFinite(Number(result.prediction_mm))||!Array.isArray(result.interval_95_mm))throw new Error('The service returned incomplete engineering evidence. Nothing was accepted.');setPrediction(result);setLastAction('Prediction verified by the engineering service. Review the evidence before moving to build.');setService('ready')}catch(e:any){setError(e?.message||'Engineering service unavailable');setService('blocked');setLastAction('The check was not accepted. Fix the connection or inputs and try again.')}finally{setBusy(false)}}
  const deviation=prediction?prediction.prediction_mm-nominal:0,statusLabel=service==='checking'?'CONNECTING…':service==='ready'?'ENGINE READY':'ACTION NEEDED',statusClass=service==='ready'?'ok':'warn',interval=useMemo(()=>prediction?.interval_95_mm||[],[prediction])
  return <main className="page wide"><div className="workspace-head"><div><div className="eyebrow">FABRIENT / ENGINEERING WORKSPACE</div><h1 className="title">Your engineering command center.</h1><p className="muted">Intent, CAD, deterministic checks, ML and evidence work together. No silent fallbacks and no fabricated results.</p></div><div className={`status ${statusClass}`} role="status" aria-live="polite">{statusLabel}</div></div>
    {service==='blocked'&&<section className="panel" style={{marginTop:16}} role="alert"><strong>The engineering service is not reachable through the application proxy.</strong><p className="error">{error||'Upstream engineering service unavailable.'}</p><p className="muted">The browser no longer calls the Render service directly, so CORS cannot break engineering actions. Retry after the upstream service is healthy.</p><button className="button" onClick={()=>{setService('checking');setError('');request('/health').then(()=>setService('ready')).catch((e:any)=>{setError(e.message);setService('blocked')})}}>Retry connection</button></section>}
    <section className="return-loop panel" style={{marginTop:16}}><div><div className="eyebrow">TODAY / NEXT BEST ACTION</div><h2>{prediction?'Review the verified prediction before build.':'Run your first deterministic check.'}</h2><p className="muted">{lastAction}</p></div><div className="loop-steps"><span className={prediction?'done':'active'}>Analyze</span><span className={prediction?'active':''}>Review</span><span>Build</span><span>Inspect</span><span>Re-verify</span></div></section>
    <div className="workspace-grid" style={{marginTop:16}}><section className="panel"><h2>01 / ENGINEERING INPUT</h2><p className="muted">These values are sent to the deterministic engineering engine. Natural-language commands are available in the Engineering Copilot.</p><div className="formgrid"><label>Nominal mm<input type="number" min="0.01" value={nominal} onChange={e=>setNominal(Math.max(.01,Number(e.target.value)||40))}/></label><label>Material<input value={material} onChange={e=>setMaterial(e.target.value)}/></label><label>Machine<input value={machine} onChange={e=>setMachine(e.target.value)}/></label><label>Process °C<input type="number" value={temp} onChange={e=>setTemp(Number(e.target.value)||245)}/></label><label>Shrinkage %<input type="number" step=".01" value={shrink} onChange={e=>setShrink(Number(e.target.value)||0)}/></label><label>Shrinkage σ %<input type="number" step=".01" min="0" value={sigma} onChange={e=>setSigma(Math.max(0,Number(e.target.value)||0))}/></label><label>Tolerance band mm<input type="number" step=".01" min="0.01" value={tolerance} onChange={e=>setTolerance(Math.max(.01,Number(e.target.value)||.4))}/></label></div><button className="button primary" onClick={predict} disabled={busy||service!=='ready'}>{busy?'Computing…':'Run deterministic prediction'}</button>{error&&service==='ready'&&<p className="error" role="alert">{error}</p>}</section>
      <section className="panel"><h2>02 / COMPUTED MODEL</h2>{!prediction?<div className="panel" style={{marginTop:12}}><strong>Nothing accepted yet.</strong><p className="muted">Run the check to create verified evidence. This state is intentional—not a blank page.</p></div>:<><div className="result-row"><div><span className="muted">PREDICTED</span><strong>{prediction.prediction_mm.toFixed(4)} mm</strong></div><div><span className="muted">95% INTERVAL</span><strong>{interval[0]?.toFixed(3)} — {interval[1]?.toFixed(3)}</strong></div><span className={`status ${prediction.status==='validated'?'ok':'warn'}`}>{prediction.status}</span></div><View3D size={[40,20,10]} deviation={deviation}/><details><summary>Technical evidence</summary><pre className="provenance">{JSON.stringify(prediction.provenance,null,2)}</pre></details></>}</section></div>
    <section className="panel" style={{marginTop:16}}><h2>03 / CONTINUE THE REAL WORK</h2><p className="muted">CAD is required for manufacturing release. Continue only after a validated STEP exists.</p><div className="row"><Link className="button primary" href="/manufacturing">Build with required STEP</Link><Link className="button" href="/projects">Projects</Link></div></section>
  </main>
}
